#!/bin/bash -x
read -p "enter branch name" branchname
git add .
read -p "enter commit name" commitName
git commit -m "adding $commitName"
git checkout master
git merge "$branchname"
git checkout $branchname
git push origin $branchname
git merge master
git checkout master
git push
